[[network.interfaces]]
name = "eth0"
address = "192.168.1.100"
netmask = "255.255.255.0"
gateway = "192.168.1.1"
dns = ["8.8.8.8", "8.8.4.4"]

[[network.interfaces]]
name = "wlan0"
address = "192.168.1.101"
netmask = "255.255.255.0"
gateway = "192.168.1.1"
ssid = "YourSSID"
password = "YourPassword"
